
bounds:-1.0	db:[10, 12, 14, 16, 18, 20, 22, 24]	Pt_max:1.0
model init: 
lambdas:{'pout': tensor([1.]), 'power': tensor([1.])},
vars:{'pout': tensor([0.]), 'power': tensor([0.])}

====================================================================================================
Traceback (most recent call last):
  File "D:\work\FC\Data_model_drive_direct-main\train\main.py", line 527, in <module>
    train_auto_pdb(False)
  File "D:\work\FC\Data_model_drive_direct-main\train\main.py", line 431, in train_auto_pdb
    x[:, -1] = pdbs[torch.randint(0, pdbs.shape[0], (x.shape[0], 1), dtype=torch.long, out=pdb)]
    ~^^^^^^^
RuntimeError: expand(torch.FloatTensor{[50, 1]}, size=[50]): the number of sizes provided (1) must be greater or equal to the number of dimensions in the tensor (2)
